#!/usr/bin/env bash

# plugin manager
git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim

# dependencies
go install golang.org/x/tools/gopls@latest

brew install ripgrep
brew install fd
brew install rust-analyzer
yarn global add bash-language-server
yarn global add pyright
yarn global add sql-language-server
yarn global add typescript typescript-language-server

# vim
yarn global add vim-language-server

# vue
yarn global add vls

# yaml
yarn global add yaml-language-server

# Lua LSP
brew install ninja
cd ~/work || exit 1
git clone https://github.com/sumneko/lua-language-server
cd lua-language-server || exit 1
git submodule update --init --recursive
cd 3rd/luamake || exit 1
compile/install.sh
cd ../..
./3rd/luamake/luamake rebuild

# Formatters
cargo install stylua --features lua52
go install mvdan.cc/sh/v3/cmd/shfmt@latest

echo "Run \`nvim +PackerInstall\` to finish setup"
